version: '3'

services: 

  backendserver:
    build: ./kafka-producer
    ports: 
      - "8081:8081"
    restart: always
    depends_on: 
      - kafka
    links:
      - kafka

  frontend:
    build: ./kafka-consumer
    links: 
      - backendserver
    depends_on: 
      - backendserver
    ports:
      - "80:80"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports: 
      - "9092:9092"
      - "9093:9093"
    environment: 
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "topic-message:1:1,topic-picture:1:1"
    depends_on: 
      - zookeeper