server:
    port: 8081
spring:
    kafka:
        consumer:
            auto-offset-reset: earliest
            group-id: test-consumer-group
        properties:
            security:
                protocol: SSL
kafka:
    address: kafka:9092
